//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.WSCUILGenerator {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/WSCUIL")]
    [System.SerializableAttribute()]
    public partial class ExceptionFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSCUILGenerator.ICUILGeneratorSVC")]
    public interface ICUILGeneratorSVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUILGeneratorSVC/DoWork", ReplyAction="http://tempuri.org/ICUILGeneratorSVC/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUILGeneratorSVC/DoWork", ReplyAction="http://tempuri.org/ICUILGeneratorSVC/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUILGeneratorSVC/GetCUIL", ReplyAction="http://tempuri.org/ICUILGeneratorSVC/GetCUILResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Agenda.WSCUILGenerator.ExceptionFaultContract), Action="http://tempuri.org/ICUILGeneratorSVC/GetCUILExceptionFaultContractFault", Name="ExceptionFaultContract", Namespace="http://schemas.datacontract.org/2004/07/WSCUIL")]
        string GetCUIL(string nombre, string apellido, string genero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUILGeneratorSVC/GetCUIL", ReplyAction="http://tempuri.org/ICUILGeneratorSVC/GetCUILResponse")]
        System.Threading.Tasks.Task<string> GetCUILAsync(string nombre, string apellido, string genero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICUILGeneratorSVCChannel : Agenda.WSCUILGenerator.ICUILGeneratorSVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CUILGeneratorSVCClient : System.ServiceModel.ClientBase<Agenda.WSCUILGenerator.ICUILGeneratorSVC>, Agenda.WSCUILGenerator.ICUILGeneratorSVC {
        
        public CUILGeneratorSVCClient() {
        }
        
        public CUILGeneratorSVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CUILGeneratorSVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CUILGeneratorSVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CUILGeneratorSVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GetCUIL(string nombre, string apellido, string genero) {
            return base.Channel.GetCUIL(nombre, apellido, genero);
        }
        
        public System.Threading.Tasks.Task<string> GetCUILAsync(string nombre, string apellido, string genero) {
            return base.Channel.GetCUILAsync(nombre, apellido, genero);
        }
    }
}
