//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agenda.WebServiceAreasContactos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceAreasContactos.AreasSoap")]
    public interface AreasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getAreasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAreas", ReplyAction="*")]
        Agenda.WebServiceAreasContactos.getAreasResponse getAreas(Agenda.WebServiceAreasContactos.getAreasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAreas", ReplyAction="*")]
        System.Threading.Tasks.Task<Agenda.WebServiceAreasContactos.getAreasResponse> getAreasAsync(Agenda.WebServiceAreasContactos.getAreasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAreasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAreas", Namespace="http://tempuri.org/", Order=0)]
        public Agenda.WebServiceAreasContactos.getAreasRequestBody Body;
        
        public getAreasRequest() {
        }
        
        public getAreasRequest(Agenda.WebServiceAreasContactos.getAreasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAreasRequestBody {
        
        public getAreasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAreasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAreasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Agenda.WebServiceAreasContactos.getAreasResponseBody Body;
        
        public getAreasResponse() {
        }
        
        public getAreasResponse(Agenda.WebServiceAreasContactos.getAreasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAreasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Agenda.WebServiceAreasContactos.ArrayOfString getAreasResult;
        
        public getAreasResponseBody() {
        }
        
        public getAreasResponseBody(Agenda.WebServiceAreasContactos.ArrayOfString getAreasResult) {
            this.getAreasResult = getAreasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AreasSoapChannel : Agenda.WebServiceAreasContactos.AreasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AreasSoapClient : System.ServiceModel.ClientBase<Agenda.WebServiceAreasContactos.AreasSoap>, Agenda.WebServiceAreasContactos.AreasSoap {
        
        public AreasSoapClient() {
        }
        
        public AreasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AreasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AreasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Agenda.WebServiceAreasContactos.getAreasResponse Agenda.WebServiceAreasContactos.AreasSoap.getAreas(Agenda.WebServiceAreasContactos.getAreasRequest request) {
            return base.Channel.getAreas(request);
        }
        
        public Agenda.WebServiceAreasContactos.ArrayOfString getAreas() {
            Agenda.WebServiceAreasContactos.getAreasRequest inValue = new Agenda.WebServiceAreasContactos.getAreasRequest();
            inValue.Body = new Agenda.WebServiceAreasContactos.getAreasRequestBody();
            Agenda.WebServiceAreasContactos.getAreasResponse retVal = ((Agenda.WebServiceAreasContactos.AreasSoap)(this)).getAreas(inValue);
            return retVal.Body.getAreasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Agenda.WebServiceAreasContactos.getAreasResponse> Agenda.WebServiceAreasContactos.AreasSoap.getAreasAsync(Agenda.WebServiceAreasContactos.getAreasRequest request) {
            return base.Channel.getAreasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Agenda.WebServiceAreasContactos.getAreasResponse> getAreasAsync() {
            Agenda.WebServiceAreasContactos.getAreasRequest inValue = new Agenda.WebServiceAreasContactos.getAreasRequest();
            inValue.Body = new Agenda.WebServiceAreasContactos.getAreasRequestBody();
            return ((Agenda.WebServiceAreasContactos.AreasSoap)(this)).getAreasAsync(inValue);
        }
    }
}
